#! /bin/sh
set -e

GRUB_DEVICE="/dev/disk/by-uuid/${GRUB_DEVICE_UUID}"
unset GRUB_DEVICE_UUID
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX boot=live plainroot union=overlay"
GRUB_DISTRIBUTOR="${GRUB_DISTRIBUTOR} Live-mode"
if test -x /etc/grub.d/10_linux ; then
	/etc/grub.d/10_linux
fi
