#! /bin/sh
set -e

GRUB_DEVICE="/dev/disk/by-uuid/${GRUB_DEVICE_UUID}"
unset GRUB_DEVICE_UUID
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX boot=live plainroot union=overlay ip=frommedia noeject"
GRUB_DISTRIBUTOR="${GRUB_DISTRIBUTOR} Live-mode"

export \
   GRUB_DEVICE \
   GRUB_CMDLINE_LINUX \
   GRUB_DISTRIBUTOR

if test -x /etc/grub.d/10_linux ; then
	/etc/grub.d/10_linux
fi
